AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    CodePipeline CFN Stack for 'cognito-restore-service' micro-service

Parameters:
  Prefix:
    Type: String
    Default: 'cognito-restore'
  Environment:
    Type: String
    Default: 'dev'
  GitHubOwner:
    Type: String
    Default: 'Blueshirt-work'
  GitHubRepositoryName:
    Type: String
    Default: 'test_cognito'
  RepoName:
    Type: String
    Default: 'cognito_restore_test'
  GitBranch:
    Type: String
    Default: 'main'
  Region:
    Type: String
    Default: 'ap-south-1'
  ResourceStackName:
    Type: String
    Default: 'cognito-restore-service-dev-stack'
  PipelineArtifactBucket:
    Type: String
    Default: 'cognito-restore-dev-pipeline-artifactsbucket'
  CodeStarConnectionArn:
    Type: String
    Default: 'arn:aws:codestar-connections:us-east-1:698032826194:connection/0e2ebc7a-a6ba-412c-9237-9b502252421c'
  Stage:
    Type: String
    Default: 'dev'
  S3Bucket:
    Type: String
    Default: 'cognito-backup-bucket-test-s3'
  S3Key:
    Type: String
    Default: 'cognito-users-backup (1).json'
  UserPoolId:
    Type: String
    Default: 'ap-south-1_OpPrIODGO'
  XrayEnabled:
    Type: String
    Default: 'true'
  Tags:
    Type: String
    Default: 'Project=CognitoRestore Service=Serverless'
  IsS3BucketExists:
    Default: "false"
    Type: String
    AllowedValues: ["true", "false"]

Conditions:
  IsS3BucketExistsCondition: !Equals [!Ref IsS3BucketExists, "true"]

Resources:
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pipeline-artifacts-${AWS::AccountId}-${AWS::Region}-${AWS::StackName}'

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${RepoName}-${Environment}-pipeline'
      ArtifactStore:
        Location: !Ref PipelineArtifactBucket
        Type: S3
      RoleArn: !GetAtt CodePipelineExecutionRole.Arn
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: SourceCodeRepo
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: !Ref CodeStarConnectionArn
                FullRepositoryId: !Sub "${GitHubOwner}/${GitHubRepositoryName}"
                BranchName: !Ref GitBranch
                OutputArtifactFormat: "CODE_ZIP"
              OutputArtifacts:
                - Name: SourceCodeAsZip
              RunOrder: 1
        - Name: BuildAndPackage
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              RunOrder: 1
              Configuration:
                ProjectName: !Ref CodeBuildProjectBuildAndPackage
              InputArtifacts:
                - Name: SourceCodeAsZip
              OutputArtifacts:
                - Name: BuildArtifactAsZip
        - Name: Deploy
          Actions:
            - Name: DeployServerless
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildProjectDeploy
              InputArtifacts:
                - Name: BuildArtifactAsZip
              RunOrder: 1

  PipelineArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PipelineArtifactBucket
      PolicyDocument:
        Statement:
          - Effect: 'Deny'
            Action: 's3:*'
            Principal: '*'
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${PipelineArtifactBucket}
              - !Sub arn:${AWS::Partition}:s3:::${PipelineArtifactBucket}/*
            Condition:
              Bool:
                aws:SecureTransport: false
          - Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub 'arn:${AWS::Partition}:s3:::${PipelineArtifactBucket}'
              - !Sub 'arn:${AWS::Partition}:s3:::${PipelineArtifactBucket}/*'
            Principal:
              AWS:
                - !GetAtt CodePipelineExecutionRole.Arn

  CodePipelineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Prefix}-${Environment}-CodePipelineRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: '*'
        - PolicyName: CodePipelineCodeAndS3Bucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Effect: Allow
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${PipelineArtifactBucket}'
                  - !Sub 'arn:${AWS::Partition}:s3:::${PipelineArtifactBucket}/*'
              - Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:PutObject'
                Effect: Allow
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${PipelineArtifactBucket}'
                  - !Sub 'arn:${AWS::Partition}:s3:::${PipelineArtifactBucket}/*'

  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${RepoName}-${Environment}
      EmptyOnDelete: false
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Prefix}-${Environment}-CodeBuildRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonCognitoPowerUser"
      Policies:
        - PolicyName: CodeBuildLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*'

  CodeBuildProjectBuildAndPackage:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: REGION
            Value: !Ref Region
          - Name: AWS_ACCOUNT_ID
            Value: !Ref "AWS::AccountId"
          - Name: AWS_ECR_REPOSITORY_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepoName}-${Environment}
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: 18
              commands:
                - echo "Installing dependencies..."
                - npm install
            build:
              commands:
                - echo "Building..."
                - npm run build
            post_build:
              commands:
                - echo "Build complete!"
                - docker build -t ${AWS_ECR_REPOSITORY_URI}:latest .
                - docker push ${AWS_ECR_REPOSITORY_URI}:latest
                - echo "Pushed Docker Image"
      TimeoutInMinutes: 30
      Name: !Sub '${Prefix}-${Environment}-BuildPackage'
      
  CodeBuildProjectDeploy:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        PrivilegedMode: true
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - echo "Deploying Serverless..."
                - serverless deploy
          artifacts:
            files:
              - '**/*'
